name: CI-CD Pipeline for Fair Lending Model

on:
  push: # Trigger the workflow on push events
    branches:
      - main # Only on the main branch

jobs:
  build-and-validate:
    runs-on: ubuntu-latest # Use a standard Linux runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Specify Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Model Training
        run: python src/train_model.py

      - name: Run Fairness Validation # The critical gatekeeper step
        run: python src/validate_fairness.py

      # This step will only run if the validation script passes (exits with 0)
      - name: If Passed, Upload Model as Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: loan-default-model
          path: ${{ github.workspace }}/loan_default_model.joblib